version: '3.7'
services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../code:/var/www
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../code:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
        - "8000:80"